# Generated by Django 4.2.5 on 2023-11-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
